baseURL = 'https://dev.patrickwthomas.net/'
languageCode = 'en-us'
title = "Hi, I'm Patrick"
theme = 'bauxite'
sectionPagesMenu = 'main'

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2
    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 3

[params]
    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/username"
    [[params.social]]
        name = "github"
        url = "https://github.com/username"
